# Generated by Django 2.2.2 on 2019-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='phone_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(default='', max_length=30),
        ),
    ]
