# Generated by Django 2.2.2 on 2019-09-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190904_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='images',
        ),
    ]
