# Generated by Django 2.2.2 on 2019-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_service_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.CharField(default='no image', max_length=30),
            preserve_default=False,
        ),
    ]
