# Generated by Django 2.2.2 on 2019-09-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='image_name',
        ),
    ]
