# Generated by Django 2.2.2 on 2019-09-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190911_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
    ]
