# Generated by Django 2.2.2 on 2019-09-10 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.client'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='serviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.service'),
        ),
    ]
