# Generated by Django 2.2.2 on 2019-09-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190904_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='images',
        ),
    ]
