# Generated by Django 2.2.2 on 2019-09-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190904_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image_name',
            new_name='image',
        ),
    ]
